import type { Track } from '../../types/track';

export const MOCK_TRACKS: Track[] = [
    {
        id: 1,
        msg: null,
        sync: true,
        title: 'Beautiful Day',
        artist: 'John Smith',
        album_artist: 'John Smith',
        composer: 'John Smith',
        album: 'Summer Collection',
        track_num: '1/12',
        length: 245.5,
        file_name: 'beautiful_day.mp3',
        file_path: '/home/user/Music/John Smith/Summer Collection/beautiful_day.mp3',
        file_path_to_relative: 'John Smith/Summer Collection/beautiful_day.mp3',
        codec: 'mp3',
        size: 5867520,
        added_date: '2024-01-15 10:30:00',
        update_date: '2024-01-15 10:30:00',
    },
    {
        id: 2,
        msg: null,
        sync: false,
        title: 'Moonlight Sonata',
        artist: 'Classical Orchestra',
        album_artist: 'Various Artists',
        composer: 'Ludwig van Beethoven',
        album: 'Classical Masterpieces',
        track_num: '3/20',
        length: 893.2,
        file_name: 'moonlight_sonata.m4a',
        file_path: '/home/user/Music/Classical/moonlight_sonata.m4a',
        file_path_to_relative: 'Classical/moonlight_sonata.m4a',
        codec: 'mp4',
        size: 12456789,
        added_date: '2024-02-20 14:22:10',
        update_date: '2024-02-20 14:22:10',
    },
    {
        id: 3,
        msg: '!',
        sync: true,
        title: 'Rock Anthem',
        artist: 'The Rockers',
        album_artist: 'The Rockers',
        composer: 'Mike Johnson',
        album: 'Greatest Hits',
        track_num: '5/15',
        length: 312.8,
        file_name: 'rock_anthem.mp3',
        file_path: '/home/user/Music/Rock/The Rockers/rock_anthem.mp3',
        file_path_to_relative: 'Rock/The Rockers/rock_anthem.mp3',
        codec: 'mp3',
        size: 7456123,
        added_date: '2024-03-10 09:15:33',
        update_date: '2024-03-10 09:15:33',
    },
    {
        id: 4,
        msg: null,
        sync: true,
        title: 'Jazz Night',
        artist: 'Smooth Jazz Band',
        album_artist: 'Smooth Jazz Band',
        composer: 'Various',
        album: 'Late Night Sessions',
        track_num: '2/8',
        length: 428.1,
        file_name: 'jazz_night.m4a',
        file_path: '/home/user/Music/Jazz/jazz_night.m4a',
        file_path_to_relative: 'Jazz/jazz_night.m4a',
        codec: 'mp4',
        size: 9123456,
        added_date: '2024-04-05 16:44:21',
        update_date: '2024-04-05 16:44:21',
    },
    {
        id: 5,
        msg: null,
        sync: false,
        title: 'Electronic Dreams',
        artist: 'DJ Synthesizer',
        album_artist: 'DJ Synthesizer',
        composer: 'DJ Synthesizer',
        album: 'Digital World',
        track_num: '7/10',
        length: 198.6,
        file_name: 'electronic_dreams.mp3',
        file_path: '/home/user/Music/Electronic/electronic_dreams.mp3',
        file_path_to_relative: 'Electronic/electronic_dreams.mp3',
        codec: 'mp3',
        size: 4732154,
        added_date: '2024-05-12 11:20:45',
        update_date: '2024-05-12 11:20:45',
    },
];
